version: "3.7"
name: "skiller-whale-core-react"
services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync:0.2.1"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/app/exercises"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: ".js .jsx .ts .tsx .html"
      IGNORE_DIRS: ".git"
    volumes:
      - ./src_js:/app/exercises/src_js:ro
      - ./src_ts:/app/exercises/src_ts:ro
      - ./attendance_id:/app/sync/attendance_id:ro
    tty: true
    stdin_open: true
  dev-server:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3500:3500"
    volumes:
      - ./server:/app/exercises/server
      - ./src_js:/app/exercises/src_js
      - ./src_ts:/app/exercises/src_ts
